### ISSUE TITLE
Figure 2 Results

### ISSUE THREAD

**Issue by RoyiAvital** [locuslab/newton_admm#1]
Hello,

I looked at your article [A Semismooth Newton Method for Fast, Generic Convex Programming](https://arxiv.org/abs/1705.00772).

Looking at Figure 2, I couldn't understand if Coordinate Descent is faster than all the others or what is going on there.

Moreover,
Which version of Coordinate Descent did yo use?

Thank You.

**Comment by riceric22** [comment]
Hi @RoyiAvital , 

1) To clarify, among the specialized solvers, coordinate descent is faster than all the others. The purpose of this figure is not to show that Newton ADMM claims state of the art performance on LASSO (since this victory is claimed by coordinate descent), but instead to show that it accelerates the performance of standard ADMM. 

2) We used coordinate descent as implemented in [sklearn](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso). 

~Eric

**Comment by RoyiAvital** [comment]
@riceric22 ,

Is Coordinate Descent the fastest solution for L1 Regularized Least Squares?
When I say fastest I mean to CPU Run Time (Not number of iterations).

Thank You.
